// client/app/components/Layout/Footer.vue
<script setup lang="ts">
import { useSettingStore } from '~/../stores/settingStore.js';

const localePath = useLocalePath();
const settingStore = useSettingStore();
defineProps({
  variant: {
    type: String,
    default: 'newsletter',
  },
});
const { locale } = useI18n();
const toast = useToast();

const email = ref('');

const _handleSubmit = () => {
  const api = useApi();
  useAsyncData('newsletter', () =>
    api.global
      .newsletter(email.value, locale.value)
      .then(() => {
        toast.success({
          title: 'Success!',
          message: 'Your action was completed successfully.',
          position: 'topRight',
        });
      })
      .catch(() => {
        toast.error({ title: 'Error!', message: 'Something went wrong.', position: 'topRight' });
      }),
  );
};
</script>

<template>
  <footer class="bg-slate-900 px-6 pb-12 pt-20 text-white lg:px-20">
    <div class="mx-auto max-w-[1400px]">
      <div class="mb-16 grid grid-cols-1 gap-12 md:grid-cols-3">
        <div class="col-span-1 md:col-span-1">
          <div class="mb-6 flex items-center gap-3">
            <div class="flex size-10 items-center justify-center rounded-lg bg-primary">
              <span class="material-symbols-outlined text-[24px] text-white">language</span>
            </div>
            <span class="text-xl font-semibold tracking-tight">Site</span>
          </div>
          <p class="text-sm leading-relaxed text-slate-400">
            A modern content management platform. Build and manage your digital presence with ease.
          </p>
        </div>
        <template
          v-if="
            settingStore.bottomMenu &&
            settingStore.bottomMenu['value'] &&
            settingStore.bottomMenu['value']['groups']
          "
        >
          <div v-for="(group, index) in settingStore.bottomMenu['value']['groups']" :key="index">
            <h3 class="mb-6 text-sm font-semibold uppercase tracking-wider text-slate-300">
              {{ group.name }}
            </h3>
            <ul v-if="group.submenu && group.submenu.length" class="space-y-3">
              <li v-for="(link, key) in group.submenu" :key="key">
                <NuxtLink
                  :to="
                    localePath({
                      name: link.link !== '' && link.link !== null ? link.link : 'index',
                    })
                  "
                  class="text-sm text-slate-400 transition-colors hover:text-white"
                >
                  {{ link.name }}
                </NuxtLink>
              </li>
            </ul>
          </div>
        </template>
      </div>
      <div
        class="flex flex-col items-center justify-between gap-6 border-t border-slate-800 pt-8 md:flex-row"
      >
        <p class="text-sm text-slate-500">
          &copy; {{ new Date().getFullYear() }} All rights reserved.
        </p>
        <div class="flex gap-6 text-sm text-slate-500">
          <a class="transition-colors hover:text-white" href="#">Privacy</a>
          <a class="transition-colors hover:text-white" href="#">Terms</a>
          <a class="transition-colors hover:text-white" href="#">Cookies</a>
        </div>
      </div>
    </div>
  </footer>
</template>

// martinhanzl.cz/components/Footer.tsx
import React from 'react';
import { MenuGroup } from '../types';

interface FooterProps {
  menuGroups: MenuGroup[];
}

const Footer: React.FC<FooterProps> = ({ menuGroups }) => {
  return (
    <footer className="py-12 bg-background-light dark:bg-background-dark border-t border-gray-200 dark:border-white/5">
      <div className="max-w-7xl mx-auto px-6">
        <div className="flex flex-col md:flex-row justify-between items-start gap-8 mb-8">
           <div className="flex flex-col gap-4">
             <div className="flex items-center gap-2">
                <div className="h-8 w-8 bg-primary rounded-lg flex items-center justify-center text-white font-bold text-sm">
                    MH
                </div>
                <span className="font-bold text-lg dark:text-white">Martin Hanzl</span>
             </div>
             <p className="text-sm text-slate-500 max-w-xs">
               Building digital experiences with modern technologies and focus on performance.
             </p>
           </div>
           
           <div className="flex gap-12 flex-wrap">
             {menuGroups.map((group, idx) => (
               <div key={idx} className="flex flex-col gap-3">
                 <h4 className="font-bold text-slate-900 dark:text-white">{group.name}</h4>
                 <div className="flex flex-col gap-2">
                    {group.submenu.map((item, subIdx) => (
                      <a 
                        key={subIdx} 
                        href={item.link ? (item.link === 'faq' ? '#faq' : '#') : '#'}
                        className="text-sm text-slate-500 hover:text-primary transition-colors"
                      >
                        {item.name}
                      </a>
                    ))}
                 </div>
               </div>
             ))}
           </div>
        </div>
        
        <div className="pt-8 border-t border-gray-200 dark:border-white/5 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-slate-500 text-sm">
            © {new Date().getFullYear()} Martin Hanzl. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
