// client/app/components/Home/Hero.vue
<script setup lang="ts">
const { t, locale } = useI18n();
</script>

<template>
  <section class="relative bg-sunny/20 py-16 lg:py-24 px-6 overflow-hidden">
    <div class="absolute -top-20 -right-20 size-80 bg-turquoise/20 blob-shape -z-10 animate-pulse"></div>
    <div class="absolute -bottom-20 -left-20 size-96 bg-primary/10 blob-shape -z-10"></div>
    <div class="max-w-6xl mx-auto flex flex-col items-center">
      <h1 class="text-6xl md:text-8xl font-black text-center mb-12 font-display leading-[0.9] text-deep-blue">
        Explore ideas <br/>
        <span class="text-primary italic underline decoration-turquoise">that matter.</span>
      </h1>
      <div class="grid grid-cols-1 lg:grid-cols-5 gap-8 items-center w-full">
        <div class="hidden lg:flex flex-col gap-6">
          <a class="group relative block aspect-[4/5] bg-turquoise rounded-portal overflow-hidden shadow-xl transform -rotate-3 hover:rotate-0 transition-transform"
             href="#">
            <div class="absolute inset-0 bg-deep-blue/20 group-hover:bg-transparent transition-colors z-10"></div>
            <div class="absolute bottom-4 left-4 z-20">
              <span class="bg-white text-deep-blue font-black px-4 py-1 text-sm rounded-full">Lifestyle</span>
            </div>
            <span class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-white material-symbols-outlined text-6xl opacity-50">spa</span>
          </a>
        </div>
        <div class="lg:col-span-3 flex flex-col items-center space-y-8">
          <p class="text-xl text-deep-blue font-medium text-center max-w-md">
            Discover stories, thinking, and expertise from writers on any topic. Curated just for you.
          </p>
          <div class="relative w-full max-w-2xl group">
            <div class="absolute -inset-2 bg-gradient-to-r from-primary via-turquoise to-sunny rounded-full blur opacity-40 group-hover:opacity-100 transition duration-1000"></div>
            <div class="relative flex items-center bg-white border-4 border-deep-blue rounded-full p-2">
              <span class="material-symbols-outlined ml-4 text-deep-blue/40">search</span>
              <input class="w-full bg-transparent border-none focus:ring-0 text-xl font-bold placeholder:text-deep-blue/20 px-4"
                     placeholder="Search for articles..." type="text"/>
              <button class="bg-primary text-white font-black rounded-full px-8 py-4 text-lg shadow-[4px_4px_0px_0px_rgba(26,83,92,1)] hover:shadow-none hover:translate-x-1 hover:translate-y-1 transition-all">
                Search
              </button>
            </div>
          </div>
        </div>
        <div class="hidden lg:flex flex-col gap-6">
          <a class="group relative block aspect-[4/5] bg-primary rounded-portal overflow-hidden shadow-xl transform rotate-3 hover:rotate-0 transition-transform"
             href="#" style="border-radius: 5rem 2rem 2rem 5rem;">
            <div class="absolute inset-0 bg-deep-blue/20 group-hover:bg-transparent transition-colors z-10"></div>
            <div class="absolute bottom-4 right-4 z-20">
              <span class="bg-white text-deep-blue font-black px-4 py-1 text-sm rounded-full">Travel</span>
            </div>
            <span class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-white material-symbols-outlined text-6xl opacity-50">flight_takeoff</span>
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

// martinhanzl.cz/components/Hero.tsx
import React from 'react';

const Hero: React.FC = () => {
  return (
    <section className="relative min-h-screen flex items-center justify-center pt-20 overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-1/4 -left-20 w-96 h-96 bg-primary/10 rounded-full blur-[100px]"></div>
        <div className="absolute bottom-1/4 -right-20 w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px]"></div>
      </div>
      
      <div className="relative z-10 max-w-5xl mx-auto px-6 text-center flex flex-col items-center gap-8 reveal-on-scroll">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary text-xs font-medium uppercase tracking-wider mb-4 animate-pulse">
          <span className="w-2 h-2 rounded-full bg-primary"></span>
          Dostupný pro nové projekty
        </div>
        
        <h1 className="font-display text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight leading-tight">
          Martin <span className="text-transparent bg-clip-text bg-gradient-to-r from-slate-900 via-slate-700 to-slate-500 dark:from-white dark:via-slate-200 dark:to-slate-400">Hanzl</span>
        </h1>
        
        <h2 className="font-body text-xl md:text-2xl text-slate-600 dark:text-slate-400 max-w-2xl font-light">
          Fullstack Web Developer vytvářející <span className="text-primary font-medium">škálovatelné digitální architektury</span> a minimalistická rozhraní.
        </h2>
        
        <div className="flex flex-wrap gap-4 mt-8 justify-center">
          <a href="#experience" className="h-12 px-8 rounded-lg border border-slate-300 dark:border-white/20 hover:border-primary dark:hover:border-primary text-slate-800 dark:text-white font-bold flex items-center gap-2 transition-all duration-300 hover:bg-slate-100 dark:hover:bg-white/5">
            Zkušenosti
            <span className="material-symbols-outlined text-[20px]">arrow_downward</span>
          </a>
          <a href="#contact" className="h-12 px-8 rounded-lg bg-primary text-white font-bold flex items-center gap-2 shadow-glow hover:shadow-glow-hover transition-all duration-300 hover:bg-primary/90 transform hover:-translate-y-0.5">
            Napište mi
            <span className="material-symbols-outlined text-[20px]">arrow_forward</span>
          </a>
        </div>
      </div>
    </section>
  );
};

export default Hero;
