// paluciny.cz/app/components/Layout/Navbar.vue
<script setup>
import { ref } from 'vue';
import { Bars3Icon, XMarkIcon } from '@heroicons/vue/24/outline';
import { useSettingStore } from '~/../stores/settingStore';

const settingStore = useSettingStore();

const localePath = useLocalePath();

const { locale } = useI18n();

const isOpen = ref(false);
const mobileMenuOpen = ref(false);
</script>

<template>
  <BaseModalContactForm :open="isOpen" @close="isOpen = false" />
  <header
    class="fixed top-0 z-50 flex w-full items-center justify-between border-b border-cream-dark bg-cream/95 px-6 py-3 backdrop-blur-sm lg:px-20"
  >
    <NuxtLink :to="locale !== 'cs' ? `/${locale}` : '/'" class="flex items-center gap-2.5">
      <div class="flex size-9 items-center justify-center rounded-full bg-forest shadow-sm">
        <span class="material-symbols-outlined text-[20px] text-white">forest</span>
      </div>
      <span class="font-display text-xl font-semibold italic tracking-tight text-earth"
        >Palu&#269;iny</span
      >
    </NuxtLink>

    <div class="flex flex-1 items-center justify-end gap-6">
      <div
        v-if="
          settingStore.topMenu &&
          settingStore.topMenu['value'] &&
          settingStore.topMenu['value']['groups']
        "
        class="hidden items-center gap-6 md:flex"
      >
        <template v-for="(group, index) in settingStore.topMenu['value']['groups']" :key="index">
          <NuxtLink
            v-if="index < settingStore.topMenu['value']['groups'].length - 1"
            :to="
              localePath({ name: group.link !== '' && group.link !== null ? group.link : 'index' })
            "
            class="text-sm font-medium text-earth transition-colors hover:text-forest"
          >
            {{ group.name }}
          </NuxtLink>
          <NuxtLink
            v-else
            :to="
              localePath({ name: group.link !== '' && group.link !== null ? group.link : 'index' })
            "
            class="rounded-full bg-forest px-6 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-forest-dark"
          >
            {{ group.name }}
          </NuxtLink>
        </template>
      </div>

      <!-- Mobile menu button -->
      <button
        class="inline-flex items-center justify-center rounded-lg p-2 text-earth hover:bg-cream-dark md:hidden"
        @click="mobileMenuOpen = !mobileMenuOpen"
      >
        <Bars3Icon v-if="!mobileMenuOpen" class="size-6" />
        <XMarkIcon v-else class="size-6" />
      </button>
    </div>
  </header>

  <!-- Mobile menu -->
  <transition
    enter-active-class="transition duration-200 ease-out"
    enter-from-class="opacity-0 -translate-y-2"
    enter-to-class="opacity-100 translate-y-0"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="opacity-100 translate-y-0"
    leave-to-class="opacity-0 -translate-y-2"
  >
    <div
      v-if="mobileMenuOpen"
      class="fixed left-0 right-0 top-[57px] z-40 border-b border-cream-dark bg-cream px-6 py-4 shadow-lg md:hidden"
    >
      <div
        v-if="
          settingStore.topMenu &&
          settingStore.topMenu['value'] &&
          settingStore.topMenu['value']['groups']
        "
        class="flex flex-col gap-2"
      >
        <NuxtLink
          v-for="(group, index) in settingStore.topMenu['value']['groups']"
          :key="index"
          :to="
            localePath({ name: group.link !== '' && group.link !== null ? group.link : 'index' })
          "
          class="rounded-lg px-3 py-2 text-sm font-medium text-earth transition-colors hover:bg-cream-dark hover:text-forest"
          @click="mobileMenuOpen = false"
        >
          {{ group.name }}
        </NuxtLink>
      </div>
    </div>
  </transition>
</template>

// martinhanzl.cz/components/Navbar.tsx
import React, { useState } from 'react';
import { MenuGroup } from '../types';

interface NavbarProps {
  menuGroups: MenuGroup[];
}

const Navbar: React.FC<NavbarProps> = ({ menuGroups }) => {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const handleNavigation = (link: string | null) => {
    if (!link) return;
    
    let href = "#";
    if (link === 'faq') href = "#faq";
    else if (link === 'blog') href = "#"; 
    else if (link.startsWith('#')) href = link;
    
    const element = document.querySelector(href);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    setMobileMenuOpen(false);
  };

  return (
    <nav className="fixed top-0 left-0 right-0 z-50 backdrop-blur-md bg-white/80 dark:bg-background-dark/80 border-b border-gray-200 dark:border-white/5 transition-all duration-300">
      <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
        <a href="#" className="flex items-center gap-2 group">
          <div className="h-8 w-8 bg-primary rounded-lg flex items-center justify-center text-white font-bold text-lg group-hover:shadow-glow transition-all duration-300">
            MH
          </div>
          <span className="font-bold text-xl tracking-tight hidden sm:block group-hover:text-primary transition-colors">Martin Hanzl</span>
        </a>

        <div className="hidden md:flex items-center gap-8 text-sm font-medium">
          <a href="#services" className="hover:text-primary transition-colors relative after:content-[''] after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-0.5 after:bg-primary after:transition-all hover:after:w-full">Služby</a>
          <a href="#experience" className="hover:text-primary transition-colors relative after:content-[''] after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-0.5 after:bg-primary after:transition-all hover:after:w-full">Zkušenosti</a>
          <a href="#projects" className="hover:text-primary transition-colors relative after:content-[''] after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-0.5 after:bg-primary after:transition-all hover:after:w-full">Projekty</a>
          <a href="#tech-stack" className="hover:text-primary transition-colors relative after:content-[''] after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-0.5 after:bg-primary after:transition-all hover:after:w-full">Technologie</a>
          
          {menuGroups.map((group, idx) => (
             group.link && group.link !== 'Home' ? (
                <button 
                  key={idx}
                  onClick={() => handleNavigation(group.link)}
                  className="hover:text-primary transition-colors relative after:content-[''] after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-0.5 after:bg-primary after:transition-all hover:after:w-full"
                >
                  {group.name}
                </button>
             ) : null
          ))}

          <a href="#contact" className="hover:text-primary transition-colors relative after:content-[''] after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-0.5 after:bg-primary after:transition-all hover:after:w-full">Kontakt</a>
        </div>

        <a href="#contact" className="hidden md:flex items-center justify-center h-10 px-6 rounded-lg bg-primary hover:bg-primary/90 text-white text-sm font-bold shadow-glow hover:shadow-glow-hover transition-all duration-300 transform hover:-translate-y-0.5">
          Kontaktujte mě
        </a>

        <button 
          className="md:hidden p-2 text-slate-600 dark:text-slate-300"
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
        >
          <span className="material-symbols-outlined">{mobileMenuOpen ? 'close' : 'menu'}</span>
        </button>
      </div>

      {/* Mobile Menu */}
      {mobileMenuOpen && (
        <div className="md:hidden absolute top-full left-0 right-0 bg-white dark:bg-background-dark border-b border-gray-200 dark:border-white/5 p-6 flex flex-col gap-4 shadow-xl">
          <a href="#services" onClick={() => setMobileMenuOpen(false)} className="text-lg font-medium hover:text-primary">Služby</a>
          <a href="#experience" onClick={() => setMobileMenuOpen(false)} className="text-lg font-medium hover:text-primary">Zkušenosti</a>
          <a href="#projects" onClick={() => setMobileMenuOpen(false)} className="text-lg font-medium hover:text-primary">Projekty</a>
          <a href="#tech-stack" onClick={() => setMobileMenuOpen(false)} className="text-lg font-medium hover:text-primary">Technologie</a>
          <a href="#contact" onClick={() => setMobileMenuOpen(false)} className="text-lg font-bold text-primary">Kontakt</a>
        </div>
      )}
    </nav>
  );
};

export default Navbar;
