// paluciny.cz/app/components/Layout/Navbar.vue
<script setup>
import { ref } from 'vue';
import { Bars3Icon, XMarkIcon } from '@heroicons/vue/24/outline';
import { useSettingStore } from '~/../stores/settingStore';

const settingStore = useSettingStore();

const localePath = useLocalePath();

const { locale } = useI18n();

const isOpen = ref(false);
const mobileMenuOpen = ref(false);
</script>

<template>
  <BaseModalContactForm :open="isOpen" @close="isOpen = false" />
  <header
    class="fixed top-0 z-50 flex w-full items-center justify-between border-b border-cream-dark bg-cream/95 px-6 py-3 backdrop-blur-sm lg:px-20"
  >
    <NuxtLink :to="locale !== 'cs' ? `/${locale}` : '/'" class="flex items-center gap-2.5">
      <div class="flex size-9 items-center justify-center rounded-full bg-forest shadow-sm">
        <span class="material-symbols-outlined text-[20px] text-white">forest</span>
      </div>
      <span class="font-display text-xl font-semibold italic tracking-tight text-earth"
        >Palu&#269;iny</span
      >
    </NuxtLink>

    <div class="flex flex-1 items-center justify-end gap-6">
      <div
        v-if="
          settingStore.topMenu &&
          settingStore.topMenu['value'] &&
          settingStore.topMenu['value']['groups']
        "
        class="hidden items-center gap-6 md:flex"
      >
        <template v-for="(group, index) in settingStore.topMenu['value']['groups']" :key="index">
          <NuxtLink
            v-if="index < settingStore.topMenu['value']['groups'].length - 1"
            :to="
              localePath({ name: group.link !== '' && group.link !== null ? group.link : 'index' })
            "
            class="text-sm font-medium text-earth transition-colors hover:text-forest"
          >
            {{ group.name }}
          </NuxtLink>
          <NuxtLink
            v-else
            :to="
              localePath({ name: group.link !== '' && group.link !== null ? group.link : 'index' })
            "
            class="rounded-full bg-forest px-6 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-forest-dark"
          >
            {{ group.name }}
          </NuxtLink>
        </template>
      </div>

      <!-- Mobile menu button -->
      <button
        class="inline-flex items-center justify-center rounded-lg p-2 text-earth hover:bg-cream-dark md:hidden"
        @click="mobileMenuOpen = !mobileMenuOpen"
      >
        <Bars3Icon v-if="!mobileMenuOpen" class="size-6" />
        <XMarkIcon v-else class="size-6" />
      </button>
    </div>
  </header>

  <!-- Mobile menu -->
  <transition
    enter-active-class="transition duration-200 ease-out"
    enter-from-class="opacity-0 -translate-y-2"
    enter-to-class="opacity-100 translate-y-0"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="opacity-100 translate-y-0"
    leave-to-class="opacity-0 -translate-y-2"
  >
    <div
      v-if="mobileMenuOpen"
      class="fixed left-0 right-0 top-[57px] z-40 border-b border-cream-dark bg-cream px-6 py-4 shadow-lg md:hidden"
    >
      <div
        v-if="
          settingStore.topMenu &&
          settingStore.topMenu['value'] &&
          settingStore.topMenu['value']['groups']
        "
        class="flex flex-col gap-2"
      >
        <NuxtLink
          v-for="(group, index) in settingStore.topMenu['value']['groups']"
          :key="index"
          :to="
            localePath({ name: group.link !== '' && group.link !== null ? group.link : 'index' })
          "
          class="rounded-lg px-3 py-2 text-sm font-medium text-earth transition-colors hover:bg-cream-dark hover:text-forest"
          @click="mobileMenuOpen = false"
        >
          {{ group.name }}
        </NuxtLink>
      </div>
    </div>
  </transition>
</template>

// web-pulse.cz/components/Navbar.tsx
import React, { useState } from 'react';
import { Locale, MenuItem } from '../types';
import { LanguageSwitcher } from './LanguageSwitcher';

interface NavbarProps {
  menuItems: MenuItem[];
  currentLocale: Locale;
  onLocaleChange: (locale: Locale) => void;
}

export const Navbar: React.FC<NavbarProps> = ({ menuItems, currentLocale, onLocaleChange }) => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  return (
    <nav className="fixed w-full z-50 bg-background-light/90 dark:bg-background-dark/90 backdrop-blur-md border-b border-gray-100 dark:border-gray-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-20">
          <div className="flex items-center gap-2">
            <span className="material-icons-round text-primary text-3xl">bolt</span>
            <span className="font-display font-bold text-xl text-slate-900 dark:text-white">
              Web-pulse
            </span>
          </div>

          {/* Desktop Menu */}
          <div className="hidden md:flex items-center space-x-8">
            <div className="flex space-x-6 font-medium">
              {menuItems.map((item, index) => (
                <a
                  key={index}
                  href={item.link ? `#${item.link}` : '#'}
                  className="text-slate-600 dark:text-slate-300 hover:text-primary dark:hover:text-primary transition"
                >
                  {item.name}
                </a>
              ))}
            </div>
            
            <LanguageSwitcher currentLocale={currentLocale} onLocaleChange={onLocaleChange} />

            <a
              className="bg-primary hover:bg-secondary text-white px-5 py-2.5 rounded-full font-semibold transition shadow-lg shadow-primary/25"
              href="#contact"
            >
              Get Started -&gt;
            </a>
          </div>

          {/* Mobile Menu Button */}
          <div className="md:hidden flex items-center gap-4">
            <LanguageSwitcher currentLocale={currentLocale} onLocaleChange={onLocaleChange} />
            <button 
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              className="text-slate-600 dark:text-slate-300 p-2"
            >
              <span className="material-icons-round text-2xl">
                {isMobileMenuOpen ? 'close' : 'menu'}
              </span>
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Menu Dropdown */}
      {isMobileMenuOpen && (
        <div className="md:hidden bg-white dark:bg-slate-900 border-b border-slate-100 dark:border-slate-800 absolute w-full left-0 top-20 shadow-xl">
            <div className="px-4 py-6 space-y-4">
              {menuItems.map((item, index) => (
                <a
                  key={index}
                  href={item.link ? `#${item.link}` : '#'}
                  onClick={() => setIsMobileMenuOpen(false)}
                  className="block text-slate-600 dark:text-slate-300 hover:text-primary dark:hover:text-primary text-lg font-medium"
                >
                  {item.name}
                </a>
              ))}
               <a
                className="block w-full text-center bg-primary hover:bg-secondary text-white px-5 py-3 rounded-xl font-semibold transition mt-6"
                href="#contact"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Get Started
              </a>
            </div>
        </div>
      )}
    </nav>
  );
};
