// web-pulse.cz/components/Footer.tsx
import React, { useState } from 'react';
import { Locale, MenuItem } from '../types';
import { apiService } from '../services/apiService';

interface FooterProps {
  menuItems: MenuItem[];
  currentLocale: Locale;
}

export const Footer: React.FC<FooterProps> = ({ menuItems, currentLocale }) => {
  const [email, setEmail] = useState('');
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');

  const handleSubscribe = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email) return;
    setStatus('loading');
    try {
      await apiService.postNewsletter(currentLocale, email);
      setStatus('success');
      setEmail('');
      setTimeout(() => setStatus('idle'), 3000);
    } catch (error) {
      console.error(error);
      setStatus('error');
    }
  };

  return (
    <footer className="bg-slate-900 text-slate-300 py-16 border-t border-slate-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 mb-12">
          {/* Brand Column */}
          <div>
            <div className="flex items-center gap-2 mb-6">
              <span className="material-icons-round text-primary text-2xl">bolt</span>
              <span className="font-display font-bold text-xl text-white">Web-pulse</span>
            </div>
            <p className="text-sm text-slate-400 mb-6">
              Crafting superior digital experiences through innovation, design, and robust engineering.
            </p>
            <div className="flex gap-4">
              {['FB', 'TW', 'IN'].map((social) => (
                <a
                  key={social}
                  className="w-8 h-8 flex items-center justify-center rounded-full bg-slate-800 hover:bg-primary hover:text-white transition cursor-pointer"
                  href="#"
                >
                  <span className="text-xs">{social}</span>
                </a>
              ))}
            </div>
          </div>

          {/* Dynamic Menu Columns */}
          {menuItems.map((group, index) => (
             <div key={index}>
                 <h4 className="text-white font-bold mb-6">{group.name}</h4>
                 <ul className="space-y-3 text-sm">
                     {group.submenu?.map((item, idx) => (
                         <li key={idx}>
                             <a href={item.link ? `#${item.link}` : '#'} className="hover:text-primary transition">
                                 {item.name}
                             </a>
                         </li>
                     ))}
                 </ul>
             </div>
          ))}

          {/* Newsletter Column */}
          <div>
            <h4 className="text-white font-bold mb-6">Newsletter</h4>
            <p className="text-sm text-slate-400 mb-4">
              Get the latest insights on tech and design.
            </p>
            <form onSubmit={handleSubscribe} className="flex flex-col gap-2">
              <div className="flex gap-2">
                <input
                    className="bg-slate-800 border-none rounded-lg px-4 py-2 text-sm w-full focus:ring-2 focus:ring-primary text-white placeholder-slate-500"
                    placeholder="Your email"
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={status === 'loading' || status === 'success'}
                />
                <button
                    type="submit"
                    disabled={status === 'loading' || status === 'success'}
                    className="bg-primary hover:bg-secondary text-white px-4 py-2 rounded-lg text-sm font-semibold transition disabled:opacity-50"
                >
                    {status === 'loading' ? '...' : 'Subscribe'}
                </button>
              </div>
              {status === 'success' && <p className="text-xs text-green-400">Subscribed successfully!</p>}
              {status === 'error' && <p className="text-xs text-red-400">Failed to subscribe.</p>}
            </form>
          </div>
        </div>

        <div className="border-t border-slate-800 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs text-slate-500">
          <div>© 2024 Web-pulse Agency. All rights reserved.</div>
          <div className="flex gap-6">
            <a className="hover:text-white" href="#">
              Privacy Policy
            </a>
            <a className="hover:text-white" href="#">
              Terms of Service
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

// client/app/components/Layout/Footer.vue
<script setup lang="ts">
import { useSettingStore } from '~/../stores/settingStore.js';

const localePath = useLocalePath();
const settingStore = useSettingStore();
defineProps({
  variant: {
    type: String,
    default: 'newsletter',
  },
});
const { locale } = useI18n();
const toast = useToast();

const email = ref('');

const _handleSubmit = () => {
  const api = useApi();
  useAsyncData('newsletter', () =>
    api.global
      .newsletter(email.value, locale.value)
      .then(() => {
        toast.success({
          title: 'Success!',
          message: 'Your action was completed successfully.',
          position: 'topRight',
        });
      })
      .catch(() => {
        toast.error({ title: 'Error!', message: 'Something went wrong.', position: 'topRight' });
      }),
  );
};
</script>

<template>
  <footer class="bg-slate-900 px-6 pb-12 pt-20 text-white lg:px-20">
    <div class="mx-auto max-w-[1400px]">
      <div class="mb-16 grid grid-cols-1 gap-12 md:grid-cols-3">
        <div class="col-span-1 md:col-span-1">
          <div class="mb-6 flex items-center gap-3">
            <div class="flex size-10 items-center justify-center rounded-lg bg-primary">
              <span class="material-symbols-outlined text-[24px] text-white">language</span>
            </div>
            <span class="text-xl font-semibold tracking-tight">Site</span>
          </div>
          <p class="text-sm leading-relaxed text-slate-400">
            A modern content management platform. Build and manage your digital presence with ease.
          </p>
        </div>
        <template
          v-if="
            settingStore.bottomMenu &&
            settingStore.bottomMenu['value'] &&
            settingStore.bottomMenu['value']['groups']
          "
        >
          <div v-for="(group, index) in settingStore.bottomMenu['value']['groups']" :key="index">
            <h3 class="mb-6 text-sm font-semibold uppercase tracking-wider text-slate-300">
              {{ group.name }}
            </h3>
            <ul v-if="group.submenu && group.submenu.length" class="space-y-3">
              <li v-for="(link, key) in group.submenu" :key="key">
                <NuxtLink
                  :to="
                    localePath({
                      name: link.link !== '' && link.link !== null ? link.link : 'index',
                    })
                  "
                  class="text-sm text-slate-400 transition-colors hover:text-white"
                >
                  {{ link.name }}
                </NuxtLink>
              </li>
            </ul>
          </div>
        </template>
      </div>
      <div
        class="flex flex-col items-center justify-between gap-6 border-t border-slate-800 pt-8 md:flex-row"
      >
        <p class="text-sm text-slate-500">
          &copy; {{ new Date().getFullYear() }} All rights reserved.
        </p>
        <div class="flex gap-6 text-sm text-slate-500">
          <a class="transition-colors hover:text-white" href="#">Privacy</a>
          <a class="transition-colors hover:text-white" href="#">Terms</a>
          <a class="transition-colors hover:text-white" href="#">Cookies</a>
        </div>
      </div>
    </div>
  </footer>
</template>
