// martinhanzl.cz/components/Hero.tsx
import React from 'react';

const Hero: React.FC = () => {
  return (
    <section className="relative min-h-screen flex items-center justify-center pt-20 overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-1/4 -left-20 w-96 h-96 bg-primary/10 rounded-full blur-[100px]"></div>
        <div className="absolute bottom-1/4 -right-20 w-[500px] h-[500px] bg-primary/5 rounded-full blur-[120px]"></div>
      </div>
      
      <div className="relative z-10 max-w-5xl mx-auto px-6 text-center flex flex-col items-center gap-8 reveal-on-scroll">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary text-xs font-medium uppercase tracking-wider mb-4 animate-pulse">
          <span className="w-2 h-2 rounded-full bg-primary"></span>
          Dostupný pro nové projekty
        </div>
        
        <h1 className="font-display text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight leading-tight">
          Martin <span className="text-transparent bg-clip-text bg-gradient-to-r from-slate-900 via-slate-700 to-slate-500 dark:from-white dark:via-slate-200 dark:to-slate-400">Hanzl</span>
        </h1>
        
        <h2 className="font-body text-xl md:text-2xl text-slate-600 dark:text-slate-400 max-w-2xl font-light">
          Fullstack Web Developer vytvářející <span className="text-primary font-medium">škálovatelné digitální architektury</span> a minimalistická rozhraní.
        </h2>
        
        <div className="flex flex-wrap gap-4 mt-8 justify-center">
          <a href="#experience" className="h-12 px-8 rounded-lg border border-slate-300 dark:border-white/20 hover:border-primary dark:hover:border-primary text-slate-800 dark:text-white font-bold flex items-center gap-2 transition-all duration-300 hover:bg-slate-100 dark:hover:bg-white/5">
            Zkušenosti
            <span className="material-symbols-outlined text-[20px]">arrow_downward</span>
          </a>
          <a href="#contact" className="h-12 px-8 rounded-lg bg-primary text-white font-bold flex items-center gap-2 shadow-glow hover:shadow-glow-hover transition-all duration-300 hover:bg-primary/90 transform hover:-translate-y-0.5">
            Napište mi
            <span className="material-symbols-outlined text-[20px]">arrow_forward</span>
          </a>
        </div>
      </div>
    </section>
  );
};

export default Hero;

// paluciny.cz/app/components/Home/Hero.vue
<script setup lang="ts"></script>

<template>
  <section class="relative overflow-hidden bg-cream">
    <!-- Full-width photo area -->
    <div class="relative min-h-[50vh] md:min-h-[65vh] lg:min-h-[75vh]">
      <!-- Background image placeholder -->
      <div class="absolute inset-0 bg-forest/20">
        <svg
          class="absolute left-1/2 top-1/2 h-32 w-32 -translate-x-1/2 -translate-y-1/2 text-forest/30"
          viewBox="0 0 100 100"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M50 10L20 50H35L15 80H85L65 50H80L50 10Z" />
          <rect x="45" y="80" width="10" height="15" />
        </svg>
      </div>

      <!-- Gradient overlay -->
      <div class="absolute inset-0 bg-gradient-to-t from-earth/40 via-transparent to-transparent" />

      <!-- Text overlay in max-width container -->
      <div
        class="relative mx-auto flex min-h-[50vh] max-w-[1200px] items-end px-6 pb-12 md:min-h-[65vh] md:pb-16 lg:min-h-[75vh] lg:px-20 lg:pb-20"
      >
        <div class="rounded-2xl bg-cream/90 p-8 backdrop-blur-sm md:max-w-lg md:p-10">
          <h1
            class="mb-3 font-display text-3xl font-bold leading-tight text-earth md:text-4xl lg:text-5xl"
          >
            S námi zažiješ dobrodružství.
          </h1>
          <p class="mb-6 text-base text-earth-light md:text-lg">
            Objevuj, hraj si a poznávej přírodu s Palučinami.
          </p>
          <NuxtLink
            to="#akce"
            class="inline-flex items-center gap-2 rounded-xl bg-forest px-6 py-3 text-base font-semibold text-white transition-colors hover:bg-forest-dark"
          >
            <span class="material-symbols-outlined text-xl">calendar_month</span>
            Kalendář akcí
          </NuxtLink>
        </div>
      </div>
    </div>
  </section>
</template>
